from __future__ import annotations

import hashlib
import json
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from .authority import classify
from .markdown import load_document, sections

PROJECT = Path("projects/chloekatastrophe")
BASELINE_FILES = (PROJECT / "overview.md", PROJECT / "AI_CONTEXT.md")
EXCLUDED_PARTS = {"generated", ".git", ".venv", "__pycache__"}
EXCLUDED_SUFFIXES = ("_prompt_audit.md",)


def discover(root: Path) -> list[Path]:
    return sorted(
        path
        for path in (root / PROJECT).rglob("*.md")
        if not EXCLUDED_PARTS.intersection(path.relative_to(root).parts)
        and not path.name.endswith(EXCLUDED_SUFFIXES)
    )


def revision(root: Path) -> str:
    supplied = os.environ.get("CANON_SOURCE_REVISION")
    if supplied:
        return supplied
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=root, text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _chunk_id(path: str, ordinal: int, heading_path: tuple[str, ...], body: str) -> str:
    # Ordinal disambiguates repeated, intentionally duplicated audit sections.
    key = "\0".join((path, str(ordinal), *heading_path, body))
    return hashlib.sha256(key.encode()).hexdigest()[:24]


def build_chunks(root: Path, source_revision: str) -> list[dict[str, object]]:
    chunks: list[dict[str, object]] = []
    for path in discover(root):
        document = load_document(root, path)
        for ordinal, section in enumerate(sections(document)):
            authority = classify(document, section)
            chunks.append(
                {
                    "id": _chunk_id(document.path, ordinal, section.heading_path, section.body),
                    "ordinal": ordinal,
                    "project": "chloekatastrophe",
                    "path": document.path,
                    "title": document.title,
                    "heading": section.heading,
                    "heading_path": list(section.heading_path),
                    "text": section.body,
                    "source_revision": source_revision,
                    "metadata": document.metadata,
                    **authority,
                }
            )
    return chunks


def build_baseline(root: Path, source_revision: str) -> str:
    parts = [
        "<!-- Generated by tools/canon-rag. Do not edit. Canon Markdown remains authoritative. -->",
        "# Chloe Katastrophe Retrieval Baseline",
        "",
        f"Source revision: `{source_revision}`",
        "",
    ]
    for relative in BASELINE_FILES:
        path = root / relative
        parts.extend((f"## Source: `{relative.as_posix()}`", "", path.read_text(encoding="utf-8").strip(), ""))
    return "\n".join(parts).rstrip() + "\n"


def write_artifacts(root: Path, output: Path) -> dict[str, object]:
    source_revision = revision(root)
    chunks = build_chunks(root, source_revision)
    output.mkdir(parents=True, exist_ok=True)
    (output / "baseline.md").write_text(build_baseline(root, source_revision), encoding="utf-8")
    with (output / "chunks.jsonl").open("w", encoding="utf-8") as stream:
        for chunk in chunks:
            stream.write(json.dumps(chunk, ensure_ascii=False, sort_keys=True) + "\n")
    manifest = {
        "schema_version": 1,
        "project": "chloekatastrophe",
        "source_revision": source_revision,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "document_count": len(discover(root)),
        "chunk_count": len(chunks),
        "artifacts": ["baseline.md", "chunks.jsonl"],
        "authority_counts": {
            authority: sum(chunk["authority"] == authority for chunk in chunks)
            for authority in sorted({str(chunk["authority"]) for chunk in chunks})
        },
    }
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest
