from __future__ import annotations

import hashlib
import json
import os
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from .assets import load_asset_records, sha256_file
from .authority import classify
from .embeddings import EmbeddingAdapter, HashEmbeddingAdapter
from .markdown import load_document, sections

PROJECT = Path("projects/chloekatastrophe")
BASELINE_FILES = (PROJECT / "overview.md", PROJECT / "AI_CONTEXT.md")
EXCLUDED_PARTS = {"generated", ".git", ".venv", "__pycache__"}
EXCLUDED_SUFFIXES = ("_prompt_audit.md",)


def discover(root: Path) -> list[Path]:
    return sorted(
        path
        for path in (root / PROJECT).rglob("*.md")
        if not EXCLUDED_PARTS.intersection(path.relative_to(root).parts)
        and not path.name.endswith(EXCLUDED_SUFFIXES)
    )


def revision(root: Path) -> str:
    supplied = os.environ.get("CANON_SOURCE_REVISION")
    if supplied:
        return supplied
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=root, text=True, stderr=subprocess.DEVNULL
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def _chunk_id(path: str, ordinal: int, heading_path: tuple[str, ...], body: str) -> str:
    # Ordinal disambiguates repeated, intentionally duplicated audit sections.
    key = "\0".join((path, str(ordinal), *heading_path, body))
    return hashlib.sha256(key.encode()).hexdigest()[:24]


def build_chunks(root: Path, source_revision: str) -> list[dict[str, object]]:
    chunks: list[dict[str, object]] = []
    for path in discover(root):
        document = load_document(root, path)
        source_sha256 = sha256_file(path)
        for ordinal, section in enumerate(sections(document)):
            authority = classify(document, section)
            chunks.append(
                {
                    "id": _chunk_id(document.path, ordinal, section.heading_path, section.body),
                    "record_type": "markdown",
                    "ordinal": ordinal,
                    "project": "chloekatastrophe",
                    "path": document.path,
                    "title": document.title,
                    "heading": section.heading,
                    "heading_path": list(section.heading_path),
                    "text": section.body,
                    "source_revision": source_revision,
                    "source_sha256": source_sha256,
                    "metadata": document.metadata,
                    **authority,
                }
            )
    return chunks + load_asset_records(root, PROJECT, source_revision)


def build_baseline(root: Path, source_revision: str) -> str:
    parts = [
        "<!-- Generated by tools/canon-rag. Do not edit. Canon Markdown remains authoritative. -->",
        "# Chloe Katastrophe Retrieval Baseline",
        "",
        f"Source revision: `{source_revision}`",
        "",
    ]
    for relative in BASELINE_FILES:
        path = root / relative
        parts.extend((f"## Source: `{relative.as_posix()}`", "", path.read_text(encoding="utf-8").strip(), ""))
    return "\n".join(parts).rstrip() + "\n"


def _load_previous(path: Path | None) -> dict[str, dict[str, object]]:
    if not path or not path.is_file():
        return {}
    records: dict[str, dict[str, object]] = {}
    with path.open(encoding="utf-8") as stream:
        for line in stream:
            record = json.loads(line)
            records[str(record["id"])] = record
    return records


def write_artifacts(
    root: Path,
    output: Path,
    *,
    previous_chunks: Path | None = None,
    full_rebuild: bool = False,
    embedder: EmbeddingAdapter | None = None,
) -> dict[str, object]:
    source_revision = revision(root)
    chunks = build_chunks(root, source_revision)
    embedder = embedder or HashEmbeddingAdapter()
    previous = {} if full_rebuild else _load_previous(previous_chunks)
    reused = 0
    for chunk in chunks:
        prior = previous.get(str(chunk["id"]))
        if prior and prior.get("source_sha256") == chunk.get("source_sha256") and isinstance(prior.get("embedding"), list):
            chunk["embedding"] = prior["embedding"]
            reused += 1
        else:
            chunk["embedding"] = embedder.embed(f"{chunk.get('title', '')}\n{chunk.get('heading', '')}\n{chunk.get('text', '')}")
    output.mkdir(parents=True, exist_ok=True)
    (output / "baseline.md").write_text(build_baseline(root, source_revision), encoding="utf-8")
    with (output / "chunks.jsonl").open("w", encoding="utf-8") as stream:
        for chunk in chunks:
            stream.write(json.dumps(chunk, ensure_ascii=False, sort_keys=True) + "\n")
    manifest = {
        "schema_version": 2,
        "project": "chloekatastrophe",
        "source_revision": source_revision,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "document_count": len(discover(root)),
        "chunk_count": len(chunks),
        "asset_count": sum(chunk.get("record_type") == "asset" for chunk in chunks),
        "embedding_adapter": embedder.name,
        "reused_embedding_count": reused,
        "full_rebuild": full_rebuild,
        "artifacts": ["baseline.md", "chunks.jsonl"],
        "authority_counts": {
            authority: sum(chunk["authority"] == authority for chunk in chunks)
            for authority in sorted({str(chunk["authority"]) for chunk in chunks})
        },
    }
    (output / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return manifest
